name: Build
on: push

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache and install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential cmake gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          version: 1.0

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.7
          actions-cache-folder: 'emsdk-cache'

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Environment Diagnostics
        run: |
          echo "--- Running Environment Diagnostics ---"
          set -x # Echo commands
          
          echo "### Tool Versions ###"
          gcc --version || echo "GCC not found or version check failed"
          g++ --version || echo "G++ not found or version check failed"
          cmake --version || echo "CMake not found or version check failed"
          arm-none-eabi-gcc --version || echo "ARM GCC not found or version check failed"
          emcc --version || echo "Emscripten (emcc) not found or version check failed"
          
          echo "### Tool Locations ###"
          which gcc || echo "GCC location not found"
          which g++ || echo "G++ location not found"
          which cmake || echo "CMake location not found"
          which arm-none-eabi-gcc || echo "ARM GCC location not found"
          which emcc || echo "Emscripten (emcc) location not found"
          
          echo "### ARM Toolchain Files ###"
          echo "Listing /usr/bin/arm-none-eabi-* ..."
          ls -l /usr/bin/arm-none-eabi-* || echo "Failed to list /usr/bin/arm-none-eabi-*"
          
          echo "Searching for nano.specs ..."
          find /usr/lib/gcc/arm-none-eabi -name nano.specs -ls || echo "nano.specs not found in /usr/lib/gcc/arm-none-eabi"
          find /usr/share/ -name nano.specs -ls 2>/dev/null || echo "nano.specs not found in /usr/share"
          echo "Checking if arm-none-eabi-gcc can find nano.specs internally..."
          arm-none-eabi-gcc --print-file-name=nano.specs || echo "ARM GCC failed to print nano.specs location"
          
          echo "### Build Script Check ###"
          ls -l ./build.sh || echo "build.sh not found or list failed"
          
          set +x
          echo "--- Environment Diagnostics Complete ---"
        shell: bash

      - name: Enhanced Environment Diagnostics
        run: |
          echo "--- Running Enhanced Environment Diagnostics ---"
          set -x # Echo commands
          
          echo "### Current Environment Variables ###"
          env | grep -E 'PATH|GCC|LIB|EMC|PYTHON|CMAKE|^LD_|EMSDK' || echo "No relevant environment variables found"
          
          echo "### CMake Toolchain Check ###"
          ls -la cmake/stm32_toolchain.cmake || echo "STM32 toolchain file not found"
          cat cmake/stm32_toolchain.cmake | head -20 || echo "Could not display toolchain file"
          
          echo "### ARM GCC Library Paths ###"
          arm-none-eabi-gcc -print-search-dirs || echo "Failed to print ARM GCC search dirs"
          arm-none-eabi-gcc -print-libgcc-file-name || echo "Failed to print libgcc file name"
          
          echo "### Simple ARM Compilation Test ###"
          echo 'int main() { return 0; }' > /tmp/test.c
          arm-none-eabi-gcc -specs=nosys.specs /tmp/test.c -o /tmp/test.elf && echo "Basic compilation works without nano.specs" || echo "Basic compilation fails without nano.specs"
          arm-none-eabi-gcc -specs=nano.specs /tmp/test.c -o /tmp/test.elf && echo "Basic compilation works with nano.specs" || echo "Basic compilation fails with nano.specs"
          
          echo "### Emscripten Configuration ###"
          em-config -v || echo "Emscripten em-config not found or failed"
          echo "EMSDK paths:"
          echo $EMSDK || echo "EMSDK env var not set"
          
          echo "### System Resources ###"
          df -h || echo "Failed to check disk space"
          free -h || echo "Failed to check memory"
          
          set +x
          echo "--- Enhanced Environment Diagnostics Complete ---"
        shell: bash

      - name: Clean previous build directories
        run: rm -rf build build-wasm build-stm32

      - name: Run build
        id: build_run
        run: ./build.sh --all
