name: Build
on: push

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential cmake gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.7
          actions-cache-folder: 'emsdk-cache'

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Check for existing build artifacts
        run: |
          echo "--- Checking for existing build artifacts ---"
          
          echo "### Checking build directories existence ###"
          [ -d "build" ] && echo "build/ directory exists" || echo "build/ directory does not exist"
          [ -d "build-wasm" ] && echo "build-wasm/ directory exists" || echo "build-wasm/ directory does not exist"
          [ -d "build-stm32" ] && echo "build-stm32/ directory exists" || echo "build-stm32/ directory does not exist"
          
          echo "### Checking for CMake cache files ###"
          [ -f "build/CMakeCache.txt" ] && echo "build/CMakeCache.txt exists" || echo "build/CMakeCache.txt does not exist"
          [ -f "build-wasm/CMakeCache.txt" ] && echo "build-wasm/CMakeCache.txt exists" || echo "build-wasm/CMakeCache.txt does not exist"
          [ -f "build-stm32/CMakeCache.txt" ] && echo "build-stm32/CMakeCache.txt exists" || echo "build-stm32/CMakeCache.txt does not exist"
          
          echo "### List content of build directories if they exist ###"
          [ -d "build" ] && echo "build/ contents:" && ls -la build/ || echo "build/ not found"
          [ -d "build-wasm" ] && echo "build-wasm/ contents:" && ls -la build-wasm/ || echo "build-wasm/ not found"
          [ -d "build-stm32" ] && echo "build-stm32/ contents:" && ls -la build-stm32/ || echo "build-stm32/ not found"
        shell: bash

      - name: Environment Diagnostics
        run: |
          echo "--- Running Environment Diagnostics ---"
          echo "Checking if arm-none-eabi-gcc exists..."
          which arm-none-eabi-gcc || echo "arm-none-eabi-gcc not found"
          echo "--- Environment Diagnostics Complete ---"
        shell: bash

      - name: Enhanced Environment Diagnostics
        run: |
          echo "--- Running Enhanced Environment Diagnostics ---"
          echo "Checking if arm-none-eabi-gcc can print nano.specs location..."
          arm-none-eabi-gcc --print-file-name=nano.specs || echo "ARM GCC failed to print nano.specs location"
          echo "--- Enhanced Environment Diagnostics Complete ---"
        shell: bash

      - name: Run build
        id: build_run
        run: ./build.sh --all
